version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-poc-drupal
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql

  drupal:
    image: drupal:latest
    container_name: poc-drupal
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      - PHP_MEMORY_LIMIT=512M
#    volumes:
#      - ./web:/opt/drupal/web
#      - ./composer.json:/opt/drupal/composer.json
#      - ./composer.lock:/opt/drupal/composer.lock
#      - ./vendor:/opt/drupal/vendor

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-poc-drupal
      MYSQL_ROOT_PASSWORD: root

volumes:
  db-data:
